server:
  port: 8025
    
logging:
  file:
    path: /home/software/image_service/logs
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true